name: gestion_integral_jyc
description: "A new Flutter project."
publish_to: "none"
version: 1.2.1+5

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_fonts: ^8.1.0
  intl: ^0.20.2
  go_router: ^17.3.0
  supabase_flutter: ^2.0.0
  flutter_riverpod: ^3.3.1
  riverpod: ^3.2.1
  flutter_dotenv: ^6.0.1
  pdf: ^3.12.0
  printing: ^5.14.3
  mobile_scanner: ^7.2.1
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  msix: ^3.18.0
  change_app_package_name: ^1.5.0

flutter:
  uses-material-design: true

  assets:
    - .env

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icons/logo.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/icons/logo.png"

msix_config:
  display_name: "Gestión J&C Impresiones 3D"
  publisher_display_name: Dédalo Studio
  identity_name: ar.com.dedalostudio.jyc
  msix_version: 1.2.1.0
  logo_path: assets/icons/logo.png
  capabilities: internetClient
  logo_padding: 0
  background_color: "#000000"
