// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcXs-BuBolArxtljjAa5sk-wmAqw8HNAI',
    appId: '1:379723516987:android:f62ae8a88b16a48186201e',
    messagingSenderId: '379723516987',
    projectId: 'gestion-jyc',
    storageBucket: 'gestion-jyc.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUKpjhyZU0UJ6YpBpvRWJK1VhlSymqw3s',
    appId: '1:379723516987:ios:990d1b437971cbcc86201e',
    messagingSenderId: '379723516987',
    projectId: 'gestion-jyc',
    storageBucket: 'gestion-jyc.firebasestorage.app',
    iosBundleId: 'ar.com.dedalostudio.gestionjyc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRjailtqi9xSF_JzI0-FT0EKm7Sfbivk0',
    appId: '1:379723516987:web:7f6daa475f01120e86201e',
    messagingSenderId: '379723516987',
    projectId: 'gestion-jyc',
    authDomain: 'gestion-jyc.firebaseapp.com',
    storageBucket: 'gestion-jyc.firebasestorage.app',
    measurementId: 'G-871X8YT9WX',
  );
}
